### ISSUE TITLE
Lisää päivämäärät rakennusten omistukselle

### ISSUE THREAD

**Issue by LKajan** [GispoCoding/jkr-core#24]
DVV-aineistosta saadaan rakennuksen omistuksen alkupvm. Tämä voitaisiin tallentaa rakennuksen_omistajat tauluun.
Loppupvm voitaisiin myös lisätä. Seuraavan importin yhteydessä siihen voitaisiin kunkin rakennuksen kohdalla antaa seuraavan omistajan alkupvm, jos kyseinen henkilö ei ole enää omistaja uudessa dvv-exportissa. Tämä ei ole täysin vedenpitävä tapa määrittää loppupäivämäärää, mutta todennäköisesti riittävä.

**Comment by Rikuoja** [comment]
Tallennettaisiinko omistuksen alku- ja loppupäivämäärät myös kohteiden osapuolille, jotka on luotu tämän tiedon perusteella?

Mitä tehtäisiin vanhimmille asukkaille, pitäisikö niillekin tallentaa alku- ja loppupäivämäärät? Asukas saattaa yhä olla paikalla, hän vain ei enää ole vanhin. Pitäisikö myös nämä tallentaa myös kohteiden osapuolille, jotka on luotu vanhimpien asukkaiden tiedon perusteella?

**Comment by TiiaY** [comment]
Laurin ehdotus on hyvä. Tällöin voi katsoa onko rakennuksen omistus vaihtunut edellisen dvv-päivityksen jälkeen.

Saman voi tehdä asukkaalle, jotta näkee, onko asukkaat vaihtuneet vai vanhin kuollut pois. Tiedoissa on näillä näkymin vain vanhin asukas.

**Comment by Rikuoja** [comment]
Lisätään siis sekä omistajille että vanhimmalle asukkaalle.

**Comment by Rikuoja** [comment]
Muutokset tehty tauluihin, mutta tässä vielä tekemättä:

- kun dvv-aineisto päivittyy, täytetään *sekä* omistuksen että vanhimman asukkeen loppupäivämäärät käyttämällä muuttuneen datan (uusi omistaja, uusi vanhin) asukas alkupäivämääriä

**Comment by Mtk112** [comment]
@TiiaY Mikä loppupäivämäärä tulisi asettaa rakennuksen omistajille / vanhimmille, kun rakennusta ei enää löydy uudesta DVV-aineistosta? Vaihtoehtoina voisi olla esimerkiksi, joku selvästi erottuva päivämäärä (esim. 01.01.3000), päivämäärä jolloin skripti on ajettu tai uuden DVV-aineiston poiminta / rekisteritilanne päivämäärä.

**Comment by Mtk112** [comment]
> Rakennuksen, kohteen, omistajan ja vanhimman asukkaan päättymispäivämäärä tilanteessa, jossa rakennus on poistunut on sama.
> 
> Mikä on sovittu kohteen päättymispäiväksi kun DVV-ajo tehdään?

Tällä hetkellä kohteiden päättymispäiväksi asetettaan käsin annettu loppupäivämäärä, jonka tarkoitus on olla päivämäärä jolloin suoritetaan päivitettäminen uudella DVV-aineistolla. Mutta esim kerrostalot luodaan ilman päättymispäivämäärää.

Jos käytetään pelkästään kohteen päättymispäivää esim. vanhimman asukkaan loppupäivän asettamiseksi, jota ei enään uudessa dvv-ainestossa ole ja asunto on tyhjillään dvv-aineiston poimintäpäivänä. Silloin tuolle poistuneelle vanhimmalle asettuu tyhjä loppupäivämäärä, jolloin käyttäjän on mahdotonta tietää, että tuo vanhin on poistunut. Samoin jos kohteelle on muokattu päättymispäivä jonnekkin tulevaisuuteen, poistunut vanhin saa virheellisesti loppupäivämääräksi tuon arvon. Tämä on kuitenkin helpompi huomata, sillä voimassaolevilla omistajilla ja vanhimilla loppupäivämäärät ovat tyhjänä.

Eli kysymyksenä @TiiaY mikä päivämäärä tulisi tälläisissa tilanteissa asettaa? Varsinkin tilanteessa jossa kohteen päättymispäivä on tyhjä.

**Comment by ltalve** [comment]
Keskusteltu palaverissa 11.5.: käytetään skriptin ajopäivää.

**Comment by Mtk112** [comment]
**Kaikki muuttuneet tiedot päivitetään:** 

Kaikki tiedot päivitetään tietokantaan.

**Perusmaksuaineistoa ei lueta uudestaan:**

Perusmaksuaineisto luetaan vain ensimmäisellä kerralla.

**Kohteen merkitsevien rakennusten lukumäärään, rakennusten omistajiin tai asukkaisiin ei muutosta:** 

Kohde pysyy ennallaan, sille voidaan lisätä esim. sauna.

**Kaikki kohteen merkitsevät rakennukset ovat poistuneet rekisteristä:** 

Kohde lakkaa.

**Yksi tai useampi kohteen useammasta merkitsevästä rakennuksesta (ei kuitenkaan kaikki)  on poistunut rekisteristä:** 

Tämä pitää tarkistaa, testaillessa poistin kohteelta asuinrakennuksen, päivittäessä / luodessa kohteet uudelleen poistettu rakennus ei palautunut kohteelle.

**Uusi merkitsevä rakennus (kohteet joissa 011 tai 041+ luonnollisen henkilön omistamat).** 

Tämä pitää tarkistaa, testaillessa poistin kohteelta asuinrakennuksen, päivittäessä / luodessa kohteet uudelleen poistettu rakennus ei palautunut kohteelle.

**Kohteen rakennuksen omistaja vaihtuu (kohteet joissa 011 tai 041+ luonnollisen henkilön omistamat).** 

Luodaan uusi kohde, vanha kohde lakkaa.

**Kohteen rakennuksen asukas vaihtunut tai tyhjälle kohteelle tullut asukas:** 

Uusi tai vaihtunut asukas luo uuden kohteen. Jos vain osa asukkaista on poistunut, ja uusia tullut tilalle, uusi kohde muodostuu. Lisäksi vanhaan kohteeseen tulee myös uudet asukkaat, ennen kuin kohde poistuu. Tämä täytyy tutkia.
