### ISSUE TITLE
Luo kohteet myös rakennuksista, joilta puuttuu kiinteistötunnus tai omistaja

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-core#31]
DVV-aineistoissa on joitakin yksittäisiä rakennuksia, joiden kiinteistötunnus tai omistaja on tuntematon. Tällä hetkellä näistä ei luoda kohteita.

**Comment by Rikuoja** [comment]
@ltalve Ei ole tehty. Eikä ole työlistallakaan, pitäisikö olla?

**Comment by TiiaY** [comment]
@Rikuoja @ltalve Molemmista pitää luoda kohteet. 

Sellaiset, joissa ei ole omistajaa ovat turvakieltoasiakkaita. Sellaiset, joista puuttuu sijaintikiinteistö, on kyse jonkin rakennusvalvonnan huonosta toiminnasta.
