### ISSUE TITLE
Liitä valinnainen sopimuksen id -kenttä kuljetukseen

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-core#32]
Tietyissä tapauksissa tuotavassa datassa ei ole riittävästi tietoja, jotta eri sopimusnumeroilla tapahtuvat saman jätelajin kuljetukset voitaisiin erotella eri kohteille tai eri aikaväleille. Tällöin voi olla tarpeen liittää kohteelle samalla aikavälillä useampia saman jätelajin sopimuksia ja kuljetuksia, ja erotella, mikä kuljetus on koskenut mitäkin sopimusta.

"Kuljetustiedoissa ei ole tietoa, missä vaiheessa kvartaalia vaihdos on tapahtunut. Sopimusnumero ei aina ole sama, koska urakoitsijat saattavat luoda asiakasnumerot eri jätekatosten sijainnin perusteella, vaikka molemmat jätekatokset ovat saman kohteen jätetiloja. Kyllä "todellisuudessa 2 eri kohdetta" olisi syytä erottaa, mutta se täytyy voida varmistaa sopimustiedoista ja olla mahdollista erottaa oikeat kuljetustiedot ja niiden sopimustiedot."

**Comment by ltalve** [comment]
Suljettu historiallinen seikka tarpeettomana.
