### ISSUE TITLE
Lisää etäisyyden tarkistus kohteiden luontiin

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-core#39]
Apparently, some perusmaksukohteet (with the same perusmaksu client id) are too large.

We should add distance check when creating kohteet of *any* kind. There is probably one already built in the code, just always run the distance check too when creating kohteet at *every* phase of adding buildings to kohteet.

**Comment by Rikuoja** [comment]
Lahden ehdotus: katsotaan, onko kohdepolygonin rakennusten välissä muita rakennuksia.

Tämä ei kuitenkaan korjaa tilannetta, jos rakennuksia on vain kaksi. Kaksi pistettä ei muodosta polygonia.

**Comment by Rikuoja** [comment]
Tampereen toteutus: rakennusten maksimietäisyys esim. 500 metriä, tai mikä tahansa etäisyys nyt onkaan sopiva.

**Comment by ltalve** [comment]
Lahdelta tähän myöhemmin näkemys, että mikä sopiva etäisyys. Pohditaan myös, onko tarve kahdelle etäisyydelle (taajama/haja-asutus).

**Comment by Rikuoja** [comment]
Ensimmäinen toteutus https://github.com/GispoCoding/jkr-core/commit/29212c63b8a9ed9b65b4c75f06979ba9aca694ea

Ryhmitellään kiinteistöjen rakennukset aina etäisyyden mukaan. Kaikki rakennukset, joista etäisyys mihin tahansa toiseen rakennukseen alle 300 metriä, kuuluvat samaan klusteriin.

Samalta kiinteistöltä voi siis syntyä useampi rakennusklusteri, jos klusterien välillä on yli 300 metriä.
