### ISSUE TITLE
Luodaan vapaa-ajanrakennukset jotenkin eri tavalla, ei perusmaksuista

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-core#40]
Perusmaksurekisterin perusteella muodostettuja vapaa-ajan asuntoja sisältäviä kohteita ei voi päivittää enää ikinä. 

On tarpeen miettiä niille uusi kohdennusscripti, joka perustuu DVV-aineistoon.

**Comment by ltalve** [comment]
Jos perusmaksuaineistoa ei ole, vapaa-ajanrakennukset luodaan ns. "perussäännöillä". Kerrostalokohteille mahdollistettava pysyvyys.

**Comment by Rikuoja** [comment]
Testataan tapahtuuko automaattisesti, jos loppupäivämäärät on asetettu oikein (kerrostaloille NULL, vapaa-ajanasunnoille tuontivuoden loppu).

**Comment by Rikuoja** [comment]
Luodaan vapaa-ajanrakennukset aina ilman perusmaksutietoja. _should_be_eternal on tässä tapauksessa tarpeeton funktio, poistetaan.

**Comment by Rikuoja** [comment]
Fixed in https://github.com/GispoCoding/jkr-core/commit/96ae30dede0dad5e1e98b1134e8d8abeb1b64725
