### ISSUE TITLE
Ihmiset mökkeilee saunoilla

### ISSUE THREAD

**Issue by Rikuoja** [GispoCoding/jkr-core#41]
Muodostettava kohde säännöllä Kiinteistöllä on sauna ja mahdollisesti muita rakennuksia. Kiinteistöstä ei muodostu muiden sääntöjen mukaan kohdetta, eli siellä ei ole huoneistoja sisältäviä rakennuksia, asuinrakennuksia tai vapaa-ajan asuinrakennuksia.

**Comment by ltalve** [comment]
Jos muita merkitseviä rakennuksia, saunasta ei tehdä uutta erillistä kohdetta omistajista riippumatta.

**Comment by ltalve** [comment]
Kysymys @TiiaY 

Lähtöoletus: Saunojen omistajat voivat olla vähän mitä sattuu, joten niistä ei tehdä yleensä erillisiä kohteita vaan ne liitetään muihin rakennuksiin. Jos päärakennuksen omistaja pysyy samana ja kohteeseen liitetään sauna omistajasta riippumatta, voi kuitenkin käydä niin että saunan omistaja muuttuu seuraavana vuonna.

Tällöin nykyiset säännöt vaativat, että kohde lopetetaan ja luodaan uusi kohde (koska saunan omistaja on muuttunut). Mutta kuitenkin uusi kohde on identtinen kuin vanha (koska sauna liitetään päärakennukseen, vaikka omistaja olisi muuttunut). Halutaanko siis silti luoda uusi kohde, vaikka vain sauna vaihtaisi omistajaa?

**Comment by TiiaY** [comment]
Nykyinen ei,  ehdotus kyllä.

**Comment by Rikuoja** [comment]
Ensimmäinen toteutus https://github.com/GispoCoding/jkr-core/commit/3db553aa80ecc8b5a8eb2165b1af48e0a85e0a4c

Ehdotetun mukainen. Pitää sitten vielä tutkia käytännössä, menevätkö saunat riittävästi oikeille kohteille ja omistajille, vai onko monilla kohteilla eri omistajien merkitseviä rakennuksia, ja menevätkö saunat tällä logiikalla liian paljon väärille omistajille?
