### ISSUE TITLE
Lisää osapuolitauluun puhelinnumero ja sähköposti

### ISSUE THREAD

**Issue by LKajan** [GispoCoding/jkr-core#8]

**Comment by ltalve** [comment]
Kuljetusdatan tuonnin yhteydessä

**Comment by ltalve** [comment]
@TiiaY Sposti- ja puhelinnumerotieto tulee kompostointi-ilmoitusaineistossa. Muiden henkilöiden osalta tietoa ei ole käytettävissä, joten tullaanko tietoja käytännössä käyttämään - ts. miten kiireellinen tämä lisäys on?

**Comment by ltalve** [comment]
12.1.2024 päätetty, että ei lisätä kenttiä eikä viedä puhelinnumeroita eikä sposteja tietokantaan.
